"use client";
import Image from "next/image";
import { useEffect, useState } from "react";
import { useApp } from '@/context/AppContext';
import { useRouter } from "next/navigation";

const carouselImages = [
  {
    src: "/blog/pureglobal-medical-device-regulatory-consulting-services.png",
    alt: "PureGlobal Medical Device Regulatory Consulting Services",
    date: "May 15, 2023",
  },
  {
    src: "/blog/neointelli-nordic-ai-consulting-enterprise-transformation.png",
    alt: "NeoIntelli Nordic AI Consulting Enterprise Transformation",
    date: "June 3, 2023",
  },
];

export const HomeHero = () => {
  const [current, setCurrent] = useState(0);
  const [fade, setFade] = useState(true);
  const { isDarkMode } = useApp();
  const router = useRouter();

  useEffect(() => {
    const timer = setInterval(() => {
      setFade(false);
      setTimeout(() => {
        setCurrent((prev) => (prev + 1) % carouselImages.length);
        setFade(true);
      }, 400);
    }, 5000);
    return () => clearInterval(timer);
  }, []);

  const goTo = (idx: number) => {
    setFade(false);
    setTimeout(() => {
      setCurrent(idx);
      setFade(true);
    }, 400);
  };

  return (
    <section className="w-full min-h-[520px] flex items-center justify-center bg-gradient-to-br from-[#f5f7ff] via-[#f8fafc] to-[#e8f0ff] dark:from-[#181c24] dark:via-[#1a1f29] dark:to-[#232a3a] py-12 px-4 transition-colors">
      <div className="max-w-[1200px] w-full flex flex-col md:flex-row items-center justify-between gap-10 md:gap-0">
        {/* 轮播图区域 */}
        <div className="relative w-full md:w-[540px] h-[340px] flex-shrink-0 flex items-center justify-center rounded-2xl shadow-2xl bg-white dark:bg-[#232a3a] overflow-hidden transition-colors">
          {/* 左按钮 */}
          <button
            className="absolute left-4 top-1/2 -translate-y-1/2 w-12 h-12 bg-[#222]/60 hover:bg-[#222]/80 active:bg-[#222]/90 rounded-full flex items-center justify-center shadow-lg transition-colors z-20"
            onClick={() => goTo((current - 1 + carouselImages.length) % carouselImages.length)}
            aria-label="Previous"
            type="button"
          >
            <svg width="28" height="28" fill="none" viewBox="0 0 24 24"><circle cx="12" cy="12" r="12" fill="none"/><path d="M15 19l-7-7 7-7" stroke="#fff" strokeWidth="2.2" strokeLinecap="round" strokeLinejoin="round"/></svg>
          </button>
          {/* 右按钮 */}
          <button
            className="absolute right-4 top-1/2 -translate-y-1/2 w-12 h-12 bg-[#222]/60 hover:bg-[#222]/80 active:bg-[#222]/90 rounded-full flex items-center justify-center shadow-lg transition-colors z-20"
            onClick={() => goTo((current + 1) % carouselImages.length)}
            aria-label="Next"
            type="button"
          >
            <svg width="28" height="28" fill="none" viewBox="0 0 24 24"><circle cx="12" cy="12" r="12" fill="none"/><path d="M9 5l7 7-7 7" stroke="#fff" strokeWidth="2.2" strokeLinecap="round" strokeLinejoin="round"/></svg>
          </button>
          <div className={`absolute inset-0 transition-opacity duration-500 ${fade ? 'opacity-100' : 'opacity-0'}`} key={current}>
            <Image
              src={carouselImages[current].src}
              alt={carouselImages[current].alt}
              fill
              className="object-contain rounded-2xl"
              priority
              sizes="(max-width: 768px) 100vw, 540px"
            />
          </div>
          {/* 顶部蓝色标签（气泡） */}
          <div className="absolute left-6 top-6 scale-90 bg-[#2563eb]/90 dark:bg-[#3b82f6]/80 text-white text-[16px] font-semibold px-5 py-1.5 rounded-full shadow-lg flex flex-col items-start transition-all select-none">
            <span>Pages Generated By Our Clients</span>
            <span className="text-xs font-normal text-blue-100 mt-0.5">Generated on {carouselImages[current].date}</span>
          </div>
        </div>
        {/* 右侧内容 */}
        <div className="flex-1 flex flex-col items-start justify-center md:pl-16 mt-10 md:mt-0">
          <div className="flex items-center mb-2">
            <Image
              src={isDarkMode ? "/icons/seopage-logo-normal.png" : "/icons/seopage-logo-light.png"}
              alt="SEOPage.ai"
              width={210}
              height={40}
              className="mb-2 h-auto"
              priority
            />
          </div>
          <h2 className="text-[38px] leading-[1.15] font-extrabold bg-gradient-to-r from-[#0ea5e9] via-[#6366f1] to-[#a855f7] bg-clip-text text-transparent mb-2">Grow Your Search<br/>Estate with AI Agent</h2>
          <p className="text-lg text-[#64748B] dark:text-[#cbd5e1] mb-6 transition-colors">Flood your funnel with pages Google and Gen-AI love.</p>
          {/* 两个按钮 */}
          <div className="flex flex-col gap-4 w-full max-w-[420px]">
            <div className="relative w-full">
              <div className="absolute right-3 -top-3 flex gap-2 z-10">
                <span className="inline-flex items-center px-2 py-0.5 rounded-full bg-[#ff4757] text-white text-xs font-bold shadow">HOT</span>
                <span className="inline-flex items-center px-2 py-0.5 rounded-full bg-[#2ed573] text-white text-xs font-bold shadow">HIGH TRAFFIC</span>
              </div>
              <button
                className="w-full h-12 pl-6 pr-4 rounded-xl bg-white dark:bg-[#232a3a] shadow-[0_4px_24px_0_rgba(80,112,255,0.10)] dark:shadow-[0_4px_24px_0_rgba(30,41,59,0.18)] text-[#222] dark:text-white font-semibold text-base text-left border border-[#e0e7ff] dark:border-[#2d3343] hover:bg-[#f5f7ff] dark:hover:bg-[#232a3a]/80 transition-all relative"
                onClick={() => router.push('/alternative')}
              >
                Go Generate Alternative Pages Right Now
              </button>
            </div>
            <div className="relative w-full">
              <div className="absolute right-3 -top-3 flex gap-2 z-10">
                <span className="inline-flex items-center px-2 py-0.5 rounded-full bg-[#ff4757] text-white text-xs font-bold shadow">HOT</span>
                <span className="inline-flex items-center px-2 py-0.5 rounded-full bg-[#2ed573] text-white text-xs font-bold shadow">HIGH TRAFFIC</span>
              </div>
              <button
                className="w-full h-12 pl-6 pr-4 rounded-xl bg-white dark:bg-[#232a3a] shadow-[0_4px_24px_0_rgba(80,112,255,0.10)] dark:shadow-[0_4px_24px_0_rgba(30,41,59,0.18)] text-[#222] dark:text-white font-semibold text-base text-left border border-[#e0e7ff] dark:border-[#2d3343] hover:bg-[#f5f7ff] dark:hover:bg-[#232a3a]/80 transition-all relative"
                onClick={() => router.push('/best')}
              >
                Go Generate Best Pages Right Now
              </button>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}; 